<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use Cocodrilo\AppBundle\Entity\Hotel;
use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Media extends BaseMedia
{
    /**
     * @var integer $id
     */
    protected $id;

//    /**
//     * @var Hotel
//     *
//     * @ORM\ManyToOne(targetEntity="Hotel", inversedBy="pictures")
//     * @ORM\JoinColumns({
//     *     @ORM\JoinColumn(name="hotel", referencedColumnName="id")
//     * })
//     */
//    private $hotel;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

//    public function getHotel()
//    {
//        return $this->hotel;
//    }
//
//    public function setHotel(Hotel $hotel)
//    {
//        $this->hotel = $hotel;
//
//        return $this;
//    }
}