app_feedback:
    resource: "@AppBundle/Resources/config/routing/feedback.yml"
    prefix:   /feedback

app_hotel:
    resource: "@AppBundle/Resources/config/routing/hotel.yml"
    prefix:   /hotel

app_homepage:
    path:     /hello/{name}
    defaults: { _controller: AppBundle:Default:index }

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }