services:
#    app.example:
#        class: Cocodrilo\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    app.admin.hotel:
        class: Cocodrilo\AppBundle\Admin\HotelAdmin
        arguments: [~, Cocodrilo\AppBundle\Entity\Hotel, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Hotel, label: Hotel}

    app.admin.image_upload:
        class: Cocodrilo\AppBundle\Admin\ImageUploadAdmin
        arguments: [~, Cocodrilo\AppBundle\Entity\ImageUpload, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Image, label: ImageUpload}
