services:
#    app.example:
#        class: Cocodrilo\AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    app.admin.hotel:
        class: Cocodrilo\AppBundle\Admin\HotelAdmin
        arguments: [~, Cocodrilo\AppBundle\Entity\Hotel, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Admin, label: Hotel}

    app.admin.image_upload:
        class: Cocodrilo\AppBundle\Admin\ImageUploadAdmin
        arguments: [~, Cocodrilo\AppBundle\Entity\ImageUpload, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Admin, label: ImageUpload}

    app.admin.slogan:
        class: Cocodrilo\AppBundle\Admin\SloganAdmin
        arguments: [~, Cocodrilo\AppBundle\Entity\Slogan, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Admin, label: Slogan}

    app.admin.feed_back:
        class: Cocodrilo\AppBundle\Admin\FeedBackAdmin
        arguments: [~, Cocodrilo\AppBundle\Entity\FeedBack, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Admin, label: FeedBack}
